# Generated by Django 5.0.6 on 2025-09-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut_pasaporte',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='equipamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitaciones/')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reservas.habitacion')),
            ],
        ),
    ]
