# Generated by Django 5.0.6 on 2025-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='precio_diario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_reserva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_reserva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
